version: '2'
services:
  db:
    image: postgres
    environment:
     POSTGRES_DB: db
  web:
    build: .
    environment:
      DEPLOY_ENV: "prod"
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
    command: dockerize -wait tcp://db:5432 bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
