version: '2'
services:
  db:
    image: postgres
    environment:
     POSTGRES_DB: bmat
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"